language: python

python:
    - "2.7"

before_install:
    - curl -L https://bootstrap.saltstack.com -o /tmp/bootstrap-salt.sh
    - sudo sh /tmp/bootstrap-salt.sh stable

install:
    - sudo service salt-minion restart
    - sudo salt-call --local grains.items
