language: python

python:
    - "2.7"

before_install:
    - curl -L https://bootstrap.saltstack.com -o /tmp/bootstrap-salt.sh
    - sudo sh /tmp/bootstrap-salt.sh stable

install:
    - sudo mkdir -p /srv/salt/states
    - sudo cp -r ./formula /srv/salt/states/formula
    - sudo cp .travis/top.sls /srv/salt/states/top.sls
    - sudo cp .travis/minion /etc/salt/minion

script:
    - sudo salt-call --local state.show_highstate
    
