sudo: required

language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

services:
    - docker

before_install:
    - docker build -t psmiraglia/ci-sandbox .
    - docker run psmiraglia/ci-sandbox
    - docker ps -a

script: python --version
